openapi: "3.0.0"
info:
  title: "Lambda API"
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: "Greets the user"
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: "The name to greet"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
